#
#   Copyright (c) 2022 Maxim Samsonov. All rights reserved.
#   This file is a part of pipc
#

name: debian

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'amd64/debian:11'
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    env:
      MAKEFLAGS: -j4
    steps:
      - name: Install packages
        run: |
          apt-get update
          apt-get -y install sudo git wget build-essential libssl-dev \
                     software-properties-common php-dev libacl1-dev   \
                     libncurses5-dev uuid-dev pkg-config

      - name: Install CMake
        run: |
          wget -nv https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.sh
          chmod a+x cmake-3.24.3-linux-x86_64.sh
          ./cmake-3.24.3-linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: pipc
          fetch-depth: 1

      - name: Checkout PHP-CPP
        if: matrix.php == '7.4'
        uses: actions/checkout@v3
        with:
          repository: CopernicaMarketingSoftware/PHP-CPP
          path: PHP-CPP
          fetch-depth: 1

      - name: Checkout PHP-CPP
        if: matrix.php == '8.1'
        uses: actions/checkout@v3
        with:
          repository: NobletSolutions/PHP-CPP
          path: PHP-CPP
          ref: php81
          fetch-depth: 1

      - name: Build and install PHP-CPP
        run: |
          cd PHP-CPP
          make
          sudo make install

      - name: Checkout iceoryx
        uses: actions/checkout@v3
        with:
          repository: eclipse-iceoryx/iceoryx
          path: iceoryx
          fetch-depth: 1

      - name: Cache iceoryx
        id: iceoryx-cache
        uses: actions/cache@v3
        with:
          path: iceoryx/build
          key: debian-iceoryx-v2.90.0-0000

      - name: Build iceoryx
        if: steps.iceoryx-cache.outputs.cache-hit != 'true'
        run: |
          cd iceoryx
          cmake -Bbuild -Hiceoryx_meta -DBUILD_ALL=ON
          cmake --build build
# or
# -DBUILD_ALL=ON
# or
# -DBUILD_TEST=ON -DINTROSPECTION=OFF -DBINDING_C=ON -DEXAMPLES=ON

      - name: Install iceoryx
        run: |
          cd iceoryx
          sudo cmake --install build

#      - name: Build pipc extension
#        run: |
#          cd pipc
#          cmake -Bbuild
#          cmake --build build
#          sudo cmake --install build

#      - name: Run tests
#        run: |
#          set -o errexit -o pipefail -o noclobber -o nounset
#          cd pipc
#          iceperf-roudi &
#          export ROUDI_PID=$!
#          sleep 1
#          php test-r.php > 1.out &
#          php test-r.php > 2.out &
#          sleep 1
#          php test.php
#          sleep 1
#          kill -SIGTERM $ROUDI_PID
#          cat 1.out
#          cat 2.out
