name: ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: pipc
          fetch-depth: 1

      - name: Install packages
        run: |
          pipc/scripts/switch_version.sh
          sudo apt install php-dev

#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '7.4'

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: CopernicaMarketingSoftware/PHP-CPP
          path: PHP-CPP
          fetch-depth: 1

      - name: Build PHP-CPP
        run: |
          cd PHP-CPP
          make -j4
          sudo make install
